# app部分のマニフェスト
# ファイル保存の可能性はありますがデプロイメントで設定しています
# php-fpmベースのため、9000/tcpで接続受け付け状態としています

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: densukest/app:in-v2
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              php artisan migrate
          initialDelaySeconds: 15
          periodSeconds: 5

        ports:
        # webと繋ぐときに使っているポート(php-fpm)
        - containerPort: 9000
        # いわゆるWebサーバーのポートはこの時点では開いていない
