# appサービス(deployment/app)をClientIPでアクセスできるようにする
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  type: ClusterIP

